FROM openjdk:21-jdk
WORKDIR /app
RUN ls -lah /  # Listar diretórios no sistema
RUN ls -lah /app  # Listar conteúdo da pasta app
COPY target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/app.jar"]